### ISSUE TITLE
Register custom post meta in gutenberg sidebar for event details

### ISSUE THREAD

**Issue by puschmie** [derknoten-wien/derknoten-wp#5]
Create a gutenberg sidebar plugin to show a 
- [ ] datetime picker for the date and time of the event
- [ ] text field for the  the person that holds the workshop
- [ ] text field for the email of the referenti
- [ ] max number of participants
https://awhitepixel.com/blog/how-to-add-post-meta-fields-to-gutenberg-document-sidebar/
